# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-15 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcomes',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
